const GET_USERS_SAGA = 'GET_USERS_SAGA';
const SET_USERS = 'SET_USERS';
const GET_DETAIL = 'GET_DETAIL';
const SAVE_DATA = 'SAVE_DATA';
const AFTER_SAVE = 'AFTER_SAVE';
const MODIFY_ITEM = 'MODIFY_ITEM';
const DELETE_ITEM = 'DELETE_ITEM';

export {  //eslint-disable-line
    GET_USERS_SAGA,
    SET_USERS,
    GET_DETAIL,
    SAVE_DATA,
    AFTER_SAVE,
    MODIFY_ITEM,
    DELETE_ITEM
};
